.travis.yml

Update travis to release on version tags.

---

deploy/operator.yaml

Fix operator yaml to pull right image.

---

pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/rbac.go

Support WaitForFirstConsumer

---

README.md
deploy/operator.yaml
pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/rbac.go

Fixed up rbac some more to work with OKD/OS/K8s

---

.travis.yml

Update travis token.

---

.travis.yml

Publish proper tag to quay.

---

.travis.yml

Still fighting travis env variables.

---

README.md

Update selinux command to modern version.

---

.travis.yml

Update travis push to properly push container

---

deploy/operator.yaml
pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go
pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/daemonset.go
tools/csv-generator.go

Don't concat the image name, just take as is.

---

deploy/operator.yaml

Fix container image to be full image.

---

tools/csv-generator.go
tools/helper/helper.go

Fix csv generator to take operator image string.

---

Dockerfile

Add csv-generator to release container
Fixes: #28 

Add csv-generator to release container

---

Makefile

Build csv-generator during make image

make image wasn't building csv-generator

---

Dockerfile

Fix: Can't find executable in image

---

vendor/golang.org/x/xerrors/LICENSE
vendor/golang.org/x/xerrors/PATENTS
vendor/golang.org/x/xerrors/README
vendor/golang.org/x/xerrors/adaptor.go
vendor/golang.org/x/xerrors/codereview.cfg
vendor/golang.org/x/xerrors/doc.go
vendor/golang.org/x/xerrors/errors.go
vendor/golang.org/x/xerrors/fmt.go
vendor/golang.org/x/xerrors/format.go
vendor/golang.org/x/xerrors/frame.go
vendor/golang.org/x/xerrors/go.mod
vendor/golang.org/x/xerrors/internal/internal.go
vendor/golang.org/x/xerrors/wrap.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
vendor/sigs.k8s.io/controller-runtime/pkg/healthz/doc.go
vendor/sigs.k8s.io/controller-runtime/pkg/healthz/healthz.go

Added missing vendor files.

---

pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/rbac.go
tools/csv-generator.go

Since we are not managing the storage class any more, don't watch storage classes.

Don't watch storage class

---

pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/rbac.go
tools/csv-generator.go

Add list/get permission on sc.

---

README.md
deploy/hostpathprovisioner_cr.yaml

Update documentation to reflect current state.

---

pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/rbac.go
tools/csv-generator.go

Allow watch on storage class

---

deploy/operator.yaml
tools/helper/helper.go

Updated deployment example script as well.

Run as user 1000, no need to be root.

---

deploy/operator.yaml
tools/helper/helper.go

Make user 1000590000 instead of 1000 to make it openshift compatible.

---

README.md
deploy/storageclass-immediate.yaml

Mark immediate binding mode as deprecated.

---

deploy/operator.yaml
pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go
tools/csv-generator.go
tools/helper/helper.go

Update CRD definition to be explainable. Aka add descriptions to all the fields.

Make hpp operator CRD 'explainable'

---

deploy/operator.yaml

Removed extra space before --- separator added by editor.

yaml file was corrupted, fixed.

---

deploy/operator.yaml

Fix operator yaml

---

deploy/operator.yaml
pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go
pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/daemonset.go

Revert boolean change

---

tools/helper/helper.go

Missed one location for the revert back to string.

---

deploy/operator.yaml
tools/csv-generator.go
tools/helper/helper.go

Missed a few spots where naming prefix was still string.

---

deploy/operator.yaml
tools/helper/helper.go

Switch to using apiextensions v1 instead of v1beta

---

contrib/README.md
contrib/export.sh
contrib/export_pv.py
contrib/import.sh
contrib/import_pv.py

Add node upgrade scripts to contrib

---

tools/yaml-dumper/yaml-dumper.go

Fix comment to say HPP instead of CDI

---

contrib/export_pv.py
contrib/import.sh

Verify "dataSource": null doesn't exist in export file.

Ensure we strip dataSource from the export as it causes issues on import

---

go.mod
go.sum

Signed-off-by: Ariel (Ori) Bar David <abardavi@redhat.com>

Add a 'replace' to handle Prometheus' versioning

---

go.sum

go mod tidy updated go.sum

---

deploy/operator.yaml
pkg/controller/hostpathprovisioner/contoller_test.go
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/daemonset.go
pkg/controller/hostpathprovisioner/rbac.go
pkg/controller/hostpathprovisioner/scc.go
pkg/controller/hostpathprovisioner/util.go

Was using the wrong object to store in last configuration causing the merge to not work.
Fixed deploy.yaml not including alpha api.
replaces #94

Fix reconcile to properly fix changes and respond to changes in the CR

---

README.md

Fix contributed by npu21, but he was unable to sign the commit.

Fix README deploy link

---

pkg/controller/hostpathprovisioner/controller.go

As these resources no longer have an ownerRef on them to the hpp,
We need to make a change to the handlers for their respective watches to reconcile properly.

Fix reconciliation for ClusterRole/Binding and SCC

---

pkg/controller/hostpathprovisioner/controller.go

Currently we are not registering a watch on SCCs;
What happens is that we conditionally register a watch on SCCs, based on if they exist in the cluster or not (OpenShift resource).
However, at the point of calling `checkSCCUsed()` the cache is not started yet, always resulting in a negative answer alongside an err:
```
"error":"the cache is not started, can not read objects"
```
Took notes from how CDI deals with a similar issue:
https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/controller/config-controller.go#L576

Fix SCCs not being watched

---

.gitignore
deploy/operator.yaml
deploy/storageclass-wffc-csi.yaml
pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
pkg/controller/hostpathprovisioner/common.go
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/csidriver.go
pkg/controller/hostpathprovisioner/daemonset.go
pkg/controller/hostpathprovisioner/rbac.go
pkg/controller/hostpathprovisioner/serviceaccount.go
tools/csv-generator.go
vendor/modules.txt

Added a new field to the CR which contains the csi plugin image.
Added a new field to the CR to disable CSI which is enabled by
default.

Support deploying CSI hpp

---

deploy/operator.yaml
pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.deepcopy.go
pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
pkg/apis/hostpathprovisioner/v1beta1/zz_generated.deepcopy.go
pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/daemonset.go
vendor/github.com/onsi/ginkgo/extensions/table/table.go
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go

Update CRD to include disableCSI for hpp CR

---

pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/csidriver.go
pkg/controller/hostpathprovisioner/daemonset.go
pkg/controller/hostpathprovisioner/rbac.go
pkg/controller/hostpathprovisioner/serviceaccount.go

Fixed disableCsi not working properly.

---

pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/csidriver.go

Allow delete of csi driver

---

pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/scc.go

Update generated SCC to use with CSI.

---

pkg/controller/hostpathprovisioner/daemonset.go

Enabled csi storage capacity configuration.

---

pkg/controller/hostpathprovisioner/daemonset.go

Report capacity for immediate binding sc.

---

go.mod
go.sum
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/daemonset.go
pkg/controller/hostpathprovisioner/scc.go
vendor/modules.txt

Modify the daemonset parameters to work with topology

---

Makefile
hack/version.sh

Print version we are releasing.
```release-note
NONE
```

Change image variable name to not clash with runner environment variable.

---

go.mod
go.sum
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/daemonset.go
pkg/controller/hostpathprovisioner/rbac.go
tools/helper/crd_generated.go
vendor/k8s.io/client-go/discovery/fake/discovery.go
vendor/modules.txt

Fixes #
```release-note
Enhancement: Snapshotting is now a feature gate.
```

Add snapshot featuregate support

---

deploy/operator.yaml
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/scc.go

The operator does not deploy the csi driver properly due to some SCC issues. This PR fixes them.
Fixes #
```release-note
NONE
```

Fix SCC creation/deletion for CSI driver.

---

Dockerfile

Fixes #
```release-note
NONE
```

Update fedora version to 34

---

pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/rbac.go

Fixes #
```release-note
NONE
```

Reconcile role and role binding created by operator

---

go.mod
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/cr.go
pkg/controller/hostpathprovisioner/prometheus.go
vendor/modules.txt

Degraded alert for HPP
Fixes #
```release-note
Degraded alert
```

Add degraded alert

---

tools/csv-generator.go

Adds missing resources to the webhook.
Fixes #
```release-note
NONE
```

Added proper resource on webhook definition

---

tools/helper/cluster_role_generated.go
tools/helper/crd_generated.go
tools/helper/operator_deployment_generated.go

Failing on d/s pipelines since missing a sync with generated
Fixes #
```release-note
NONE
```

Sync generated resources

---

deploy/operator.yaml
tools/helper/role_generated.go

The new mechanism wants to update the config map and is unable to do so.
Fixes #
```release-note
NONE
```

Fix permissions after updating leader election mechanism.

---

README.md
deploy/hostpathprovisioner_pvctemplate_cr.yaml

There are several modes in the hpp CR, add documentation and examples for them.
Fixes #
```release-note
NONE
```

Document storage pools in hpp CR

---

README.md

Fixes #
```release-note
NONE
```

Mention minimum k8s version

---

pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/csidriver.go

Fixes #
```release-note
None
```

Enable ephemeral volumes in CSIDriver object

---

tools/helper/helper.go

The function was not setting the value on the array, but the slice which doesn't update the underlying array. This changes the function to update the underlying array instead.
Fixes #
```release-note
BugFix: csv-generator now properly updates operator deployment environment variables from arguments.
```

Fix CSV generator to update operator deployment environment variables

---

tools/csv-generator.go

Update the example so the UI will show an updated example instead of the old example.
Fixes #
```release-note
NONE
```

Update ALM example to show new format.

---

pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/controller_test.go

Fixes #
```release-note
BugFix: HPP CR was never updated on failed healed status.
```

Fix MarkFailed not being updated in CR properly

---

pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/storagepool.go

The update to the hpp CR caused by the condition heart beat time would cause another reconcile, which updated the heart beat time which would cause an another reconcile, etc, etc. Also the pvcs order was not determined and could cause unneeded reconciles.
Fixes #
```release-note
NONE
```

Stop endless reconcile

---

README.md

Updated README.md to include instructions on installing the cert-manager which is now a requirement for the operator.
Fixes #220
```release-note
NONE
```

include cert-manager installation instructions

---

pkg/controller/hostpathprovisioner/controller.go

When the node selector changed the cleanup jobs were run, but never cleaned
after they finished. This makes sure the cleanup is run after the jobs are
finished when the node selector changes.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2068269
```release-note
BugFix: Cleanup cleanup jobs when node selector changes.
```

Fix cleanup jobs not being removed when node selector changes

---

CONTRIBUTING.md

Fixes #224 
```release-note
NONE
```

Add missing CONTRIBUTING.md file

---

README.md

Fixes #240 
```release-note
NONE
```

Minor changes to README's "How to deploy"

---

deploy/operator.yaml
go.mod
go.sum
tools/helper/crd_generated.go
vendor/k8s.io/api/core/v1/generated.proto
vendor/k8s.io/api/core/v1/types.go
vendor/modules.txt

https://github.com/kubernetes/kubernetes/pull/114617
Fixes #
```release-note
NONE
```

Temporarily consume stray commit to overcome k8s bug

---

pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook.go
pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/csidriver.go
pkg/controller/hostpathprovisioner/daemonset.go
pkg/controller/hostpathprovisioner/prometheus.go
pkg/controller/hostpathprovisioner/scc.go
pkg/controller/hostpathprovisioner/serviceaccount.go
pkg/controller/hostpathprovisioner/storagepool.go
pkg/controller/hostpathprovisioner/storagepool_test.go

Should unblock CI which is currently not running unit tests at all: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_hostpath-provisioner-operator/307/pull-hostpath-provisioner-operator-unit-test/1648615823150944256
Fixes #
```release-note
NONE
```

Fix revive lint errors

---

hack/build-crd-generator.sh
hack/build-csv-generator.sh
hack/build-mounter.sh
hack/build-operator.sh
tools/helper/operator_deployment_generated.go

The release was creating statically linked binaries and there is no particular reason for this. Doing dynamically linked binaries would decrease the container size.
Update deprecated registry references to the current ones
Fixes #
```release-note
NONE
```

Allow dynamic linking of binaries

---

hack/build-csv-generator.sh

Fixes #
```release-note
NONE
```

Correct typo in csv generator build command

---

cmd/mounter/mounter_suite_test.go
cmd/mounter/mounter_test.go
pkg/apis/hostpathprovisioner/v1beta1/api_suite_test.go
pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go
pkg/client/clientset/versioned/fake/register.go
pkg/client/clientset/versioned/scheme/register.go
pkg/controller/hostpathprovisioner/controller_suite_test.go
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/cryptopolicy_test.go
pkg/controller/hostpathprovisioner/csidriver_test.go
pkg/controller/hostpathprovisioner/daemonset_test.go
pkg/controller/hostpathprovisioner/rbac_test.go
pkg/controller/hostpathprovisioner/scc_test.go
pkg/controller/hostpathprovisioner/serviceaccount_test.go
pkg/controller/hostpathprovisioner/storagepool.go
pkg/controller/hostpathprovisioner/storagepool_test.go
version/version.go
version/version_suite_test.go
version/version_test.go

Fix some linter errors that snuck in while the check was not working.
Fixes #
```release-note
NONE
```

Fix linter errors

---

Makefile
hack/build-crd-generator.sh
hack/build-csv-generator.sh
hack/build-mounter.sh
hack/build-operator.sh
hack/common.sh
hack/run-unit-tests.sh

Ensure the go version is set to 1.20.8 before building binaries. Defaults to 1.20.8
Fixes #
```release-note
NONE
```

Ensure the go version is set to 1.20.8

---

go.mod
go.sum
vendor/github.com/emicklei/go-restful/.travis.yml
vendor/github.com/emicklei/go-restful/CHANGES.md
vendor/github.com/emicklei/go-restful/Makefile
vendor/github.com/emicklei/go-restful/README.md
vendor/github.com/emicklei/go-restful/container.go
vendor/github.com/emicklei/go-restful/cors_filter.go
vendor/github.com/emicklei/go-restful/jsr311.go
vendor/github.com/emicklei/go-restful/parameter.go
vendor/github.com/emicklei/go-restful/request.go
vendor/github.com/emicklei/go-restful/response.go
vendor/github.com/emicklei/go-restful/route.go
vendor/github.com/emicklei/go-restful/route_builder.go
vendor/github.com/emicklei/go-restful/route_reader.go
vendor/github.com/emicklei/go-restful/service_error.go
vendor/github.com/emicklei/go-restful/web_service.go
vendor/modules.txt

Update go-restful to fix CVE.
Fixes #
```release-note
NONE
```

Update go-restful to 2.16.0

---

README.md
docs/dev-getting-started.md

Add dev-getting-started doc with steps to test a pr using hpp. 
In addition this pr reverts the changes made
here:https://github.com/kubevirt/hostpath-provisioner-operator/pull/409.
Fixes #
```
Added a developer guide for testing a pr
```

Add dev-getting-started doc

---

pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/daemonset_test.go

Not sure how this happened but the linter was unhappy about some unused variables.
Fixes #
```release-note
NONE
```

Fix linter complaining about unused variables

---

deploy/operator.yaml
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/rbac.go
tools/helper/cluster_role_generated.go
tools/helper/role_generated.go

There are no major breaches as far as I can tell, so this is just getting rid of some unneeded verbs.
Fixes #
https://issues.redhat.com/browse/CNV-32812
```release-note
BugFix: Global permissions [*] seen across hostpath provisioner
```

Audit RBAC, ensure no global (*) permissions

---

Dockerfile
Makefile
hack/build-crd-generator.sh
hack/build-csv-generator.sh
hack/build-mounter.sh
hack/build-operator.sh
hack/common.sh
hack/run-unit-tests.sh

Setting the version manually was breaking the image release of latest (and possibly branches as well once we make a new one)
Also update the container to build fedora 39 instead of 36.
Fixes #
```release-note
NONE
```

Use golang available in builder container instead of trying to set it manually.

---

go.mod
go.sum

Bump Go to 1.21, so we can bump packages that are based on it.
```release-note
None
```

Bump Go to 1.21

---

pkg/controller/hostpathprovisioner/controller.go
pkg/controller/hostpathprovisioner/daemonset_test.go

Fixes #
```release-note
NONE
```

[release-v0.18] Fix revive errors

---

pkg/controller/hostpathprovisioner/daemonset_test.go

Fixes #
```release-note
NONE
```

[release-v0.17] fix revive errors

---

deploy/operator.yaml
pkg/controller/hostpathprovisioner/controller_test.go
pkg/controller/hostpathprovisioner/rbac.go
pkg/controller/hostpathprovisioner/util.go
tools/helper/cluster_role_generated.go

Fixes #
```release-note
BugFix: PVs of HPP are stuck Terminating
```

[release-v0.20] Add PV patch RBAC for external provisioner sidecar

---

go.mod

See https://github.com/kubevirt/containerized-data-importer/pull/3496
Fixes #
```release-note
NONE
```

[release-v0.22] Standardize setting go.mod to minor

---

go.mod

See https://github.com/kubevirt/containerized-data-importer/pull/3496
Fixes #
```release-note
NONE
```

Standardize setting go.mod to minor

---

renovate.json

feat: add custom renovate config
```release-note
feat: add custom renovate config
```

feat: add custom renovate config

---

pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook.go
pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go

When I updated the validator to use the new CustomValidator interface, it stopped working.
Forgot to update the manager to include the validator. So it never started.
```release-note
NONE
```

Fix validator not working
