kubevirt/hostpath-provisioner-operator

Makefile
Signed-off-by: Adam Litke <alitke@redhat.com>
=> Remove -trimpath which is only available in golang-1.13

Makefile
Signed-off-by: Adam Litke <alitke@redhat.com>
=> Remove golang 1.13 specific optional compiler flag

README.md, deploy/operator.yaml, deploy/storageclass-immediate.yaml, deploy/storageclass-wffc.yaml, pkg/controller/hostpathprovisioner/contoller_test.go, pkg/controller/hostpathprovisioner/controller.go
1. Allows user to pick Immediate or WaitForFirstConsumer, so operator is useful for older kubernetes.
2. Allows user to pick the storage class name.
=> Don't manage storage class with operator.

deploy/operator.yaml, pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go, pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go, pkg/controller/hostpathprovisioner/contoller_test.go, pkg/controller/hostpathprovisioner/daemonset.go, tools/helper/helper.go
Switched useNamingPrefix to be a boolean in validation.
=> Changed useNamingPrefix to be a boolean instead of string.

README.md, contrib/machineconfig-selinux-hpp.yaml
These used to reside in CDI as:
cluster-sync/okd-4.3/hpp-master-mc.yaml
cluster-sync/okd-4.3/hpp-worker-mc.yaml
Combine the two into one file and refer to them in the README.
---
I combined the two files "blindly" since I don't have an easily available
way of testing it. Hopefully it's fine and the description is right.
=> Add a MachineConfig file for SELinux-specific configuration

tools/helper/helper.go, tools/yaml-dumper/yaml-dumper.go
Added tool to dump CRD from code to yaml so we can compare against the operator.yaml CRD
=> Fixed CRD definition in helper, so csv-generator has proper CRD

contrib/export_pv.py
When testing the export.sh script in my cluster, the script reports an unknown flag error. Seems like the --export flag is no longer supported. However removing the flag has no adverse effects on functionality and import/export works fine without it.
Fixes #85 
Signed-off-by: David Critch <dcritch@gmail.com>
=> Removing obsolete argument

cmd/manager/main.go, pkg/controller/hostpathprovisioner/contoller_test.go
Currently SCCs are not being watched due to incorrect scheme setup of openshift/api/security:
https://github.com/openshift/api/blob/master/security/v1/register.go#L21-L22
=> Change how scheme is set up for openshift/api/security

pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/rbac.go, pkg/controller/hostpathprovisioner/scc.go, pkg/controller/hostpathprovisioner/serviceaccount.go
In https://github.com/kubevirt/hostpath-provisioner-operator/pull/106 we introduced constant resource names,
instead of resource names that depend on the CR's name.
This requires special handling in an upgrade scenario, where we might end up with two sets of hpp resources,
If user was using a custom CR name.
Example:
- Pre upgrade
CR name: "custom-hostpath-provisioner"
Resource names: DaemonSet called "custom-hostpath-provisioner", SA "custom-hostpath-provisioner-admin"
- Post upgrade
SA, DS now have fixed names ("hostpath-provisioner", "hostpath-provisioner-admin").
They don't exist, we proceed to create them
We now have 2 DaemonSets acting on PVCs.
=> Handle upgrade scenario according to constant resource names

deploy/operator.yaml, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/rbac.go, pkg/controller/hostpathprovisioner/scc.go, pkg/controller/hostpathprovisioner/serviceaccount.go, tools/csv-generator.go
Upon uprade with custom CR name, was failing to cleanup the extra set of resources
that are name dependent (context in #106).
The issue was that we only give delete permissions to the fixed names,
and hence we cant expect the operator to be able to delete the old duplicate set.
=> Handle upgrade unable to delete duplicate set of resources

pkg/controller/hostpathprovisioner/common.go, pkg/controller/hostpathprovisioner/controller_suite_test.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/rbac.go, pkg/controller/hostpathprovisioner/scc.go, pkg/controller/hostpathprovisioner/serviceaccount.go, pkg/controller/hostpathprovisioner/util.go, tools/helper/helper.go
We should be able to tell if we're part of a broader installation,
and also make sure no resources of ours seem like :alien: to the user.
Will follow up in https://github.com/kubevirt/hostpath-provisioner
to make sure our PVs are labeled with those as well.
=> Add relationship labels

pkg/controller/hostpathprovisioner/daemonset.go
Currently upgrade is failing because latest is adding labels (https://github.com/kubevirt/hostpath-provisioner-operator/pull/114) to spec.selector.
In any case it would not make sense to reconcile this field, as:
- It is immutable
- spec.selector is a minimal set that is needed to know which pods are under our governance,
while spec.template.metadata.labels can have extra labels which we can label the pods with.
=> Don't reconcile over spec.selector changes

pkg/controller/hostpathprovisioner/daemonset.go
Currently the maximum number of replicas that can be unavailable during the update process is 1,
which can be a problem in upgrades on large clusters (120 nodes, for example) as this will slow down the upgrade process.
Let's follow OpenShift conventions and set it to 10%:
https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#upgrade-and-reconfiguration
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1990063
```release-note
BugFix: maxUnavailable set to 1 which leads to …
```
=> Change MaxUnavailable amount of replicas during update from 1->10%

deploy/operator.yaml, tools/helper/helper.go
Set a minimum request on operator deployment so it doesn't get evicted as
easily.
=> Set requests on operator deployment

Makefile, go.sum, hack/build-csv-generator.sh, hack/build-operator.sh, hack/common.sh, pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go, pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go, pkg/client/clientset/versioned/fake/register.go, pkg/client/listers/hostpathprovisioner/v1alpha1/hostpathprovisioner.go, pkg/client/listers/hostpathprovisioner/v1beta1/hostpathprovisioner.go
Instead of installing go ourselves, we can use a container that has
golang already and we can use that instead.
```release-note
NONE
```
=> Update tests and release scripts to use golang containers in PROW

deploy/hostpathprovisioner_cr.yaml, deploy/operator.yaml, deploy/storageclass-wffc-csi.yaml, pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go, pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go, pkg/controller/hostpathprovisioner/common.go, pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/csidriver.go, pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/rbac.go, pkg/controller/hostpathprovisioner/scc.go, pkg/controller/hostpathprovisioner/serviceaccount.go, tools/csv-generator.go
Note that this PR will cause the operator to completely ignore disableCsi, and always deploy both daemonsets. Follow up PRs will allow one to toggle either one on or off.
```release-note
NONE
```
=> Modify operator to deploy both legacy and csi driver by default.

Makefile
Pass the tag to the version script so the operator gets the proper tag instead of v0.0.1
```release-note
NONE
```
=> Pass the tag to the version script so the operator gets the

pkg/controller/hostpathprovisioner/daemonset.go
We set the namespace passed to the csi-provisioner from the operator namespace, but we should pass it from the daemonset namespace in case that is different from the operator namespace.
Fixes #
```release-note
NONE
```
=> Get namespace from daemonset namespace instead of operator namespace

hack/git-askpass.sh, hack/release.sh
release.sh was pointing to non existing script. This PR fixes it.
Fixes #
```release-note
NONE
```
=> Fix release script pointing to non existing script

pkg/controller/hostpathprovisioner/csidriver.go
Driver does not support fsGroup yet, so set to none. Basically this means the driver will not respect fsGroup set on a pod.
Fixes #
```release-note
NONE
```
=> Set CSIDriver FSGroupPolicy to be none

deploy/operator.yaml, pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go, pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go, pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go, pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
listType=set is not supported if the elements of the list are either object or array https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/validation/validation.go#L851-L863 switching to atomic, since the hpp operator will modify all the conditions at once.
Fixes #
```release-note
NONE
```
=> Switch listType to atomic

deploy/operator.yaml, tools/crd-generator/crd-generator.go, tools/csv-generator.go, tools/helper/crd_generated.go, tools/helper/helper.go, tools/helper/operator_deployment_generated.go
The csv generator was updated to pull generated output from operator.yaml, except for the operator deployment which is important for the csi driver to work with the HCO
Fixes #
```release-note
NONE
```
=> Generate operator deployment in csv-generator

tools/helper/helper.go
The current priority class for the operator is openshift-user-critical. This priority class does not exist in Kubernetes.
Instead, use the kubevirt-cluster-critical priority class that is created by HCO.
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
Fixes #158
```release-note
Replace the priorityClass to kubevirt-cluster-critical
```
=> Replace the priorityClass to kubevirt-cluster-critical

Makefile
We see an error in generate-crds on downstream pipelines related to `go get`ting,
but in fact we don't have to since the updated CRD is already there.
Fixes #
```release-note
NONE
```
=> Drop crd-generator from csv-generator target

pkg/controller/hostpathprovisioner/daemonset.go
Request some minimum cpu/mem so we don't get evicted first due to not having them set.
Fixes #
```release-note
NONE
```
=> Ensure the daemonset pods all have cpu/mem request set.

pkg/controller/hostpathprovisioner/prometheus.go
Avoids this spam in operator log:
```bash
{"level":"info","ts":1636476553.5133832,"logger":"controller_hostpathprovisioner","msg":"DIFF","Request.Namespace":"","Request.Name":"hostpath-provisioner","obj":{"apiVersion":"v1","kind":"Service","namespace":"hostpath-provisioner","name":"hpp-prometheus-metrics"},"patch":"[{\"op\":\"replace\",\"path\":\"/metadata/creationTimestamp\",\"value\":null},{\"op\":\"remove\",\"path\":\"/metadata/resourceVersion\"},{\"op\":\"remove\",\"path\":\"/metadata/managedFields\"},{\"op\":\"remove\",\"path\":\"/metadata/uid\"},{\"op\":\"remove\",\"path\":\"/spec/sessionAffinity\"},{\"op\":\"remove\",\"path\":\"/spec/ipFamilyPolicy\"},{\"op\":\"remove\",\"path\":\"/spec/intern …
```
=> Fix how we reconcile the prometheus resources to avoid spam

pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go
Relationship labels have slipped in to our immutable .spec.selector section
of the daemonset, which is problematic on upgrade;
- We're trying to update the pod's label values (version=newVersion)
- We get ```selector does not match template labels```, which is true because the selector will always have the old values (immutable)
.spec.selector is a minimal set that is needed to know which pods are under our governance, and is immutable,
and hence we should not have relationship labels there.
Fixes # …
=> Don't put unnecessary labels in .spec.selector

pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go
Relationship labels have slipped in to our immutable .spec.selector section
of the daemonset, which is problematic on upgrade;
- We're trying to update the pod's label values (version=newVersion)
- We get ```selector does not match template labels```, which is true because the selector will always have the old values (immutable)
.spec.selector is a minimal set that is needed to know which pods are under our governance, and is immutable,
and hence we should not have relationship labels there.
Fixes # …
=> [release-v0.10] Manual cherrypick of #170

cmd/manager/main.go
On upgrades the leader election would check before starting the ready probe this would make the leader election fail because the original pod wasn't deleted because the ready probe on the new operator would fail, since it was waiting on the leader election.
Passed the leader election setup directly into the manager, which knows how to orchestrate this.
Fixes #
```release-note
NONE
```
=> Change how leader election works in combination with ready probe

pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/csidriver.go, pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/daemonset_test.go, pkg/controller/hostpathprovisioner/prometheus.go, pkg/controller/hostpathprovisioner/rbac.go, pkg/controller/hostpathprovisioner/scc.go, pkg/controller/hostpathprovisioner/scc_test.go, pkg/controller/hostpathprovisioner/serviceaccount.go, pkg/controller/hostpathprovisioner/serviceaccount_test.go
Also refactor some of the reconcile code to use common pattern and reduce code copy and paste.
Fixes #
```release-note
Enhancement: Only start legacy provisioner if legacy CR is provided.
```
=> Only start legacy provisioner on legacy CR

pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/storagepool.go, pkg/controller/hostpathprovisioner/storagepool_test.go
Fixes #
```release-note
BugFix: Legacy CR would cause the storage pool status to be append constantly instead of replaced.
```
=> Fix bug where the legacy storage pool kept being added to the status.

pkg/controller/hostpathprovisioner/daemonset.go
If the path didn't exist on the host, the pod would not get created because the path wasn't there. Switched to directoryOrCreate which will create the directory if it doesn't exist.
Fixes #
```release-note
NONE
```
=> Fix bug where path was not being created if it didn't exist on the host already.

deploy/operator.yaml, pkg/controller/hostpathprovisioner/common.go, pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/rbac.go, pkg/controller/hostpathprovisioner/serviceaccount.go, tools/csv-generator.go, tools/helper/cluster_role_generated.go, tools/helper/helper.go, tools/helper/operator_deployment_generated.go, tools/helper/role_generated.go
The csi external health monitor does not yet support distributed health monitor controller https://github.com/kubernetes-csi/external-health-monitor/issues/87 So there is no reason to deploy it for the hpp at this point.
Fixes #
```release-note
NONE
```
=> Stop deploy the csi external health monitor

pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/prometheus.go
We want to be able to list all kubevirt alerts so we added labels to
differentiate them.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
Added common labels into alert definitions
```
=> Add common labels into alert definitions

README.md, pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook.go, pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go, pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/storagepool.go, pkg/controller/hostpathprovisioner/storagepool_test.go
Fixed bug with finalizer being always applied even if it didn't change. Causing a lot of concurrency issues.
Fixed bug where the PVC contained the storage class name, and not the storage pool name.
Don't allow duplicate paths or names.
Fixes #
```release-note
Enhancement: Allow multiple storage pools.
```
=> Remove 1 storage pool limit

pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook.go, pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/daemonset_test.go, pkg/controller/hostpathprovisioner/storagepool.go, pkg/controller/hostpathprovisioner/storagepool_test.go, pkg/controller/hostpathprovisioner/util.go
There are length limits on labels and volume names, that could be exceeded if node names + storage pool names exceeded this limit. This PR will hash the value so it will never exceed the limits. Hash the generated names if length > 63 characters (label, volume name). Also put some limits on the storage pool names. Don't allow storage pool names over 50 characters. And limits on the path lengths. Don't allow paths over 255 characters.
Fixes #184 
```release-note
Enhancement: Limit storage pool …
```
=> Hash names if length over label or volume name max

pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/daemonset.go
Relationship labels have slipped in to our immutable .spec.selector section
of the daemonset, which is problematic on upgrade;
- We're trying to update the pod's label values (version=newVersion)
- We get ```selector does not match template labels```, which is true because the selector will always have the old values (immutable)
.spec.selector is a minimal set that is needed to know which pods are under our governance, and is immutable,
and hence we should not have relationship labels there.
Fixes # …
=> [release-v0.9] Manual cherrypick of #170

pkg/controller/hostpathprovisioner/csidriver.go, pkg/controller/hostpathprovisioner/daemonset.go
Fixes #
```release-note
Enhancement: CSI driver now respects fsGroup podSecurityContext
```
=> Update CSI driver to allow for fsGroup policy.

pkg/controller/hostpathprovisioner/csidriver.go, pkg/controller/hostpathprovisioner/csidriver_test.go, pkg/controller/hostpathprovisioner/rbac_test.go, pkg/controller/hostpathprovisioner/scc_test.go
In k8s 1.19 we hit an infinite CSIDriver delete-recreate loop:
```bash
{"level":"info","ts":1639565904.80454,"logger":"controller_hostpathprovisioner","msg":"DIFF","Request.Namespace":"","Request.Name":"hostpath-provisioner","obj":{"apiVersion":"storage.k8s.io/v1","kind":"CSIDriver","name":"kubevirt.io.hostpath-provisioner"},"patch":"[{\"op\":\"add\",\"path\":\"/spec/storageCapacity\",\"value\":true},{\"op\":\"add\",\"path\":\"/spec/fsGroupPolicy\",\"value\":\"None\"}]"}
{"level":"info","ts":1639565904.804589,"logger":"controller_hostpathprovisioner","msg":"Deleting CSIDriver so we can update","Request.Namespace":"","Request.Name":"hostpath-provisioner","CSIDriver.Name":"kubevirt.io.hostpath-provisio …
```
=> Don't delete/update over immutable CSIDriver fields

pkg/controller/hostpathprovisioner/storagepool.go, pkg/controller/hostpathprovisioner/storagepool_test.go
Fixes #
```release-note
NONE
```
=> Ensure storage pool deployment sets service account

pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/prometheus.go
Prometheus recording rule (rule[i].Record != "") can't have an annotations field:
```bash
admission webhook \"prometheusrules.openshift.io\" denied the request: Rules are not valid
```
```bash
$ oc create -f rules.yaml
The  "prometheusrules" is invalid: : 8:13: group "hpp.rules", rule 1, "kubevirt_hpp_operator_up_total": invalid field 'annotations' in recording rule
```
https://github.com/prometheus/prometheus/blob/main/model/rulefmt/rulefmt.go#L182
Fixes #
```release-note
NONE
```
=> Remove annotations from prometheus recording rules

tools/csv-generator.go
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
This PR fixes the JSON format of the `alm-examples` annotation in the CSV.
Fixes #208
```release-note
fixes issue 208
```
=> Fix the JSON format of the CSV's `alm-examples` field

pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/storagepool.go, pkg/controller/hostpathprovisioner/storagepool_test.go
On an hpp CR that has both basic and pvcTemplate storage pool, removing the CR would cause a npe.
For example if you use a template that uses ceph as its pvcTemplate.
```yaml
apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
name: hostpath-provisioner
spec:
imagePullPolicy: Always
storagePools:
- name: local-basic
path: "/var/local-basic"
- name: local-pvc-template
pvcTemplate:
volumeMode: Block   # Can be Filesystem
storageClassName: rook-ceph-block
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 5Gi
path: "/var/hpvolumes"
workload:
nodeSelector:
kubernetes.io/os: linux
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
=> Fix issue with basic and pvcTemplate causing npe when removing hpp cr

pkg/controller/hostpathprovisioner/daemonset.go, pkg/controller/hostpathprovisioner/daemonset_test.go, pkg/controller/hostpathprovisioner/prometheus.go
We do this by adding the prometheus service label + port to the container.
Fixes #
```release-note
NONE
```
=> Make DaemonSet metrics scrapable

tools/helper/helper.go
The generator was replacing the image but not the env variable.
Fixes #
```release-note
NONE
```
=> Replace operator image environment variable during csv generation.

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
Meant to address a denial of service vulnerability CVE-2022-21698
https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p
```release-note
Update github.com/prometheus/client_golang to v1.11.1 as it contains a security fix
```
=> Update github.com/prometheus/client_golang to v1.11.1

tools/csv-generator.go
…cTemplate.accessModes".
Error "Invalid value: "string": spec.storagePools.pvcTemplate.accessModes in body must be of type array: "string"" for field "spec.storagePools.pvcTemplate.accessModes".
Default template when in Create HostPathProvisioner YAML View of OpenShift Web Console contains incorrect type.
```release-note
Change spec.storagePools.pvcTemplate.accessModes to array of strings in alm-examples 
```
=> Use array: "string" for "spec.storagePools.pvcTemplate.accessModes" in alm-examples

pkg/controller/hostpathprovisioner/controller.go
The watches didn't start when prometheus was not enabled
on the cluster, this caused some of the roles to not
be reconciled properly.
Fixes #
```release-note
NONE
```
=> Fix role/binding and service watch not starting

pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/prometheus.go
This PR adds a boolean label to each of HPP alerts, so that we can differentiate between alerts that are related to infrastructure, and alerts that are related to vmi. 
For more info, please see [#7796](https://github.com/kubevirt/kubevirt/pull/7796).
Signed-off-by: assafad [aadmi@redhat.com](mailto:aadmi@redhat.com)
```release-note
None
```
=> Add an infra label to each of HPP alerts

pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/prometheus.go
Reverts [#239](https://github.com/kubevirt/hostpath-provisioner-operator/pull/239). The design is not yet agreed as a standard for all operators alerts, so this label won't be used for now.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
None
```
=> Revert infra_label for HPP alerts

Makefile
hostpath-provisioner-operator part of fixing https://github.com/kubevirt/hostpath-provisioner/issues/98, we also need to change project-infra for both projects.
```release-note
Use buildah and podman, enable building multi-arch manifests
```
=> Use buildah instead of docker, support multi-arch builds

Dockerfile, cmd/manager/main.go, deploy/operator.yaml, go.mod, pkg/apis/apis.go, pkg/controller/add_hostpathprovisioner.go
Modify operator deployment so it can run in restricted seccomp profile backport of #263
Fixes #
```release-note
NONE
```
=> [release-v0.13] Modify operator deployment so it can run in restricted seccomp profile

Dockerfile, pkg/controller/hostpathprovisioner/storagepool.go
If the mounter pod does not run as root it cannot mount volumes from the pvcTemplate into the host. This silently fails and the hostpath provisioner uses the host filesystem instead of the volume we want it to use. This is almost impossible to detect except with the alert we already have indicating that the hostpath provisioner is using the node filesystem.
Fixes #
```release-note
NONE
```
=> Change mounter pod to run as root

pkg/controller/hostpathprovisioner/controller_test.go, pkg/controller/hostpathprovisioner/prometheus.go
Signed-off-by: assafad <aadmi@redhat.com>
This PR adds to each of HPP alerts a label named `operator_health_impact`, which indicates how the alerts impact the operator health. This will enable us filtering alerts based on their impact on the operator health, and to later have an operator health metric, which will tell the user what is the aggregated operator health.
This label gets one of the following values:
- `critical` indicates that the alert fires due to an issue that impacts the operator's functionality badly, and an action must be taken immediately in order to solve it.
-  `warning` indicates that the alert fires due to an issue that soon might impact the operator's functionality badly, and the user should be warned in order to solve the …
=> Add `operator_health_impact` label to HPP alerts

hack/build-crd-generator.sh, hack/build-csv-generator.sh, hack/build-mounter.sh, hack/build-operator.sh
Previously the flags were:
-ldflags '-extldflags "-static"'
Or: "Pass the flag -static to the linker"
We removed the "-static" part in #318, so we don't need these flags any more.
This seems to be harmless on our CI, but when I've built the code with a different Go compiler/ld, it caused the binary to crash.
Fixes #
```release-note
NONE
```
=> Fix crash with different Go compiler: remove extra flags in build command

tools/csv-generator.go
Also, make the description text to be with similar structure as the HyperConverged resource in OLM UI.
This is to make some consistency over the user-deployable resources via the UI.
See screenshot below.
Fixes #
```release-note
NONE
```
=> [Cosmetic] Capitalize `HostPathProvisioner Deployment` in CSV DisplayName

pkg/controller/hostpathprovisioner/controller.go, pkg/controller/hostpathprovisioner/controller_test.go
ConditionAvailable was not updated to False, so kubevirt_hpp_cr_ready was not updated to 0, and HPPNotReady was not fires.
**Which issue(s) this PR fixes**:
Fixes bz #2213255
Func test coverage to be added in [hostpath-provisioner](https://github.com/kubevirt/hostpath-provisioner/blob/main/tests/prometheus_test.go#L137-L157)
```release-note
Update HPP CR conditions correctly when degraded
```
=> Update HPP CR conditions correctly when degraded

pkg/controller/hostpathprovisioner/storagepool.go, pkg/controller/hostpathprovisioner/storagepool_test.go
We are only slapping the labels on the managing resource (Deployment/Job)
and thus the labels are missing on the pod itself
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2187524
```release-note
BugFix: hpp-pool-* pods missing relationship labels
```
=> Add relationship labels to pods created by storage pool

cmd/manager/main.go, pkg/controller/hostpathprovisioner/prometheus.go, pkg/controller/hostpathprovisioner/scc.go
We dropped the "Namespace" knob as part of the migration to ctrl runtime 0.16,
https://github.com/kubevirt/hostpath-provisioner-operator/pull/372/files#diff-435eecb1d2af40ee96747f88ab71eb2758da989c92f76dcb1f714fc1b300c633L92
this means the cached client attempts to watch all resources cluster-wide.
This PR changes that to the previous behavior of only caching the specific hpp namespace.
Fixes #
```release-note
BugFix: Only cache hpp namespace
```
=> Only cache hpp ns as we did previously

cmd/mounter/main.go, pkg/controller/hostpathprovisioner/common.go, pkg/controller/hostpathprovisioner/storagepool.go, pkg/controller/hostpathprovisioner/storagepool_test.go
NFS PVCs need to be looked up by target instead of the source from findmnt. First try by source, and if the source is not found try looking up the target using the source.
Fixed some minor usage of pointer and other minor linter issues.
Updated the default csi-provisioner container to be newer so it works on newer k8s versions.
Fixes #377 
```release-note
BugFix: Handle NFS PVC templates properly
```
=> Handle NFS pvcs

README.md
When copying the bash commands it copy it with the `$` sign which is less comfortable since I needed to go to the start of the line and delete the sign when deploying.
```release-note
none
```
=> Fix readme bash commands

deploy/operator.yaml
Need to give some extra lease permissions to theoperator, so it can give those permissions to the csi-provisioner sidecar.
Fixes #
```release-note
NONE
```
=> Restore permissions to lease in the deployment namespace so the operator can give them to the csi-provisioner

pkg/monitoring/metrics/metrics.go
Before https://github.com/kubevirt/hostpath-provisioner-operator/pull/405, HPO was using `controller-runtime` metrics registry to register the operator metrics. In that PR, since its using the defaults, it started using Prometheus client-go registry.
This PR reverts to using the `controller-runtime` metrics
Fixes #
```release-note
Revert to using controller-runtime registry for metrics
```
=> Revert to using controller-runtime registry for metrics

Makefile, go.mod, go.sum, hack/run-unit-tests.sh, pkg/monitoring/rules/rules_test.go, vendor/github.com/grafana/regexp/.gitignore, vendor/github.com/grafana/regexp/LICENSE, vendor/github.com/grafana/regexp/README.md, vendor/github.com/grafana/regexp/backtrack.go, vendor/github.com/grafana/regexp/exec.go, vendor/github.com/grafana/regexp/onepass.go, vendor/github.com/grafana/regexp/regexp.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go, vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go, vendor/modules.txt
Apply the following linters:
- [monitoringlinter](https://github.com/kubevirt/monitoring/tree/main/monitoringlinter) that was implemented in https://github.com/kubevirt/monitoring/pull/221, and was designed to enforce https://github.com/kubevirt/community/pull/219.
This linter ensures that all monitoring-related practices are implemented within the `pkg/monitoring` directory using [operator-observability](https://github.com/machadovilaca/operator-observability/tree/main) methods. It verifies that all metrics, alerts and recording rules registrations are centralized in this directory, and restricts the direct use of [Prometheus registration methods](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Registerer).
Example for a message …
=> Apply monitoring linters
